
--방명록 테이블 작성
CREATE TABLE VISIT(
	NO	NUMBER(5) NOT NULL
	,WRITER VARCHAR2(20) NOT NULL
	,MEMO VARCHAR2(4000) NOT NULL
	,REGDATE DATE NOT NULL
	,CONSTRAINT VISIT_PK PRIMARY KEY(NO)
);

--시퀀스 작성
CREATE SEQUENCE VISIT_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE


