/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-16 04:18:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fileupload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.tomcat.util.http.fileupload.impl.FileCountLimitExceededException;

public final class fileselect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	public String getParam(HttpServletRequest request, String paramName){
		if(request.getParameter(paramName) != null){
			return request.getParameter(paramName);
		} else {
			return "";
		}
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.apache.tomcat.util.http.fileupload.impl.FileCountLimitExceededException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("utf-8");

	int filecounter = 0;
	if(request.getParameter("addcnt") != null && !request.getParameter("addcnt").equals("")){
		try {
			filecounter = Integer.parseInt(request.getParameter("addcnt"));
		} catch(NumberFormatException e) {
			filecounter = 0;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>파일 업로드</title>\r\n");
      out.write("	<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		// 파일 개수 입력 후 확인 버튼 눌렀을 때\r\n");
      out.write("		function addFile(formName){\r\n");
      out.write("			if(formName.addcnt.value.trim() == \"\"){\r\n");
      out.write("				alert(\"입력할 파일 개수를 입력하고 확인 버튼을 눌러주세요.\");\r\n");
      out.write("				formName.addcnt.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			formName.submit();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// DONE 버튼 눌렀을 때 검증 및 전송\r\n");
      out.write("		function elementCheck(form2){\r\n");
      out.write("			// 1. 첫 번째 폼(fileName1)의 입력값들을 두 번째 폼(frmName2)의 hidden 필드에 복사\r\n");
      out.write("			var form1 = document.fileName1;\r\n");
      out.write("			form2.txtUser.value = form1.user.value;\r\n");
      out.write("			form2.txtTitle.value = form1.title.value;\r\n");
      out.write("			form2.txtAbstract.value = form1.abstract.value;\r\n");
      out.write("\r\n");
      out.write("			// 2. 파일 첨부 여부 체크\r\n");
      out.write("			var paramIndex = 1;\r\n");
      out.write("			for(var idx = 0; idx < form2.elements.length; idx++){\r\n");
      out.write("				if(form2.elements[idx].type == \"file\"){\r\n");
      out.write("					if(form2.elements[idx].value == \"\"){\r\n");
      out.write("						var message = paramIndex + \"번째 파일 정보가 누락되었습니다. 업로드할 파일을 선택해주세요.\";\r\n");
      out.write("						alert(message);\r\n");
      out.write("						form2.elements[idx].focus();\r\n");
      out.write("						return;\r\n");
      out.write("					}\r\n");
      out.write("					paramIndex++;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 3. 전송\r\n");
      out.write("			form2.action = \"fileView.jsp\";\r\n");
      out.write("			form2.submit();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body topmargin=\"100\">\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<font color=\"#0000ff\" size=\"2\">\r\n");
      out.write("			여러개의 파일의 업로드 하려면 파일 개수를 입력한 후<br>\r\n");
      out.write("			확인 버튼을 눌러 주세요.<br>\r\n");
      out.write("			입력이 완료되면 DONE버튼을 눌러주세요.\r\n");
      out.write("		</font>\r\n");
      out.write("	</div><br>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"\" method=\"post\" name=\"fileName1\">\r\n");
      out.write("		<table width=\"75%\" border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"2\" bordercolor=\"#660000\" bgcolor=\"#ffff99\">\r\n");
      out.write("			<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("				<td width=\"10%\"><div align=\"right\">user</div></td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"text\" name=\"user\" value=\"");
      out.print(getParam(request,"user"));
      out.write("\">\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"10%\"><div align=\"right\">title</div></td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"text\" name=\"title\" value=\"");
      out.print(getParam(request,"title"));
      out.write("\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("				<td width=\"15%\"><div align=\"right\">abstract</div></td>\r\n");
      out.write("				<td width=\"50%\" colspan=\"3\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<textarea rows=\"3\" cols=\"40\" name=\"abstract\">");
      out.print(getParam(request,"abstract"));
      out.write("</textarea>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<div align=\"center\">\r\n");
      out.write("						<font size=\"-2\"> 추가할 파일 수 입력</font>\r\n");
      out.write("						<input type=\"text\" name=\"addcnt\" value=\"");
      out.print(filecounter > 0 ? filecounter : "");
      out.write("\">\r\n");
      out.write("						<input type=\"button\" value=\"확인\" onclick=\"addFile(this.form)\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"\" name=\"frmName2\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<input type=\"hidden\" name=\"txtUser\" value=\"");
      out.print(getParam(request,"user"));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"txtTitle\" value=\"");
      out.print(getParam(request,"title"));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"txtAbstract\" value=\"");
      out.print(getParam(request,"abstract"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("		<table width=\"75%\" border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"2\" bordercolor=\"#660000\" bgcolor=\"#ffff99\">\r\n");
      out.write("			<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("				<td width=\"80%\">\r\n");
      out.write("					");
 if(filecounter == 0) { 
      out.write("\r\n");
      out.write("						<div align=\"center\" style=\"font-size: 12px; color: gray;\">위에서 파일 개수를 입력하고 확인을 누르면 여기에 파일 선택창이 나타납니다.</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					");
 for(int i=0; i<filecounter; i++){ 
      out.write("\r\n");
      out.write("						<input type=\"file\" size=\"50\" name=\"selectFile");
      out.print(i);
      out.write("\" style=\"margin: 4px 0;\"><br>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"20%\" align=\"center\">\r\n");
      out.write("					<input type=\"button\" value=\"DONE\" onclick=\"elementCheck(this.form)\" style=\"padding: 10px 20px;\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
