/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-17 00:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fileupload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.reflect.Field;
import com.oreilly.servlet.MultipartRequest;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import java.util.*;
import java.io.*;

public final class fileView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.lang.reflect.Field");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");

	request.setCharacterEncoding("utf-8");

	String readFolder = "";
	String saveFolder = "upload";
	String encType="utf-8";
	int maxSize = 10*1024*1024;
	ServletContext context = getServletContext();
	readFolder = context.getRealPath(saveFolder);
	
	ArrayList saveFiles = new ArrayList();
	ArrayList origFiles = new ArrayList();
	
	String paramUser = "";
	String paramTitle="";
	String paramAbstract="";
	
	try{
		
		MultipartRequest multi = new MultipartRequest(request,readFolder,maxSize,encType,new DefaultFileRenamePolicy());
		paramUser = multi.getParameter("txtUser");
		paramTitle = multi.getParameter("txtTitle");
		paramAbstract = multi.getParameter("txtAbstract");
		
		Enumeration files = multi.getFileNames();
		
		// [수정] nextElement() 중복 호출로 인한 오류를 hasMoreElements()로 수정
		while(files.hasMoreElements()){
			String name = (String)files.nextElement();
			if(multi.getFilesystemName(name) != null) {
				saveFiles.add(multi.getFilesystemName(name));
				origFiles.add(multi.getOriginalFileName(name));
			}
		}
		

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>업로드 결과</title>\r\n");
      out.write("<link href=\"style.csss\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"75%\" border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"2\" bordercolor=\"#660000\" bgcolor=\"#ffff99\">\r\n");
      out.write("	<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("		<td width=\"10%\" bgcolor=\"#ffcc00\">\r\n");
      out.write("			<div align=\"right\"> \r\n");
      out.write("				<strong>user</strong>\r\n");
      out.write("			</div>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"30%\" bgcolor=\"#ffcc00\">\r\n");
      out.write("			");
      out.print(paramUser );
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"10%\" bgcolor=\"#ffcc00\">\r\n");
      out.write("			<div align=\"right\"> \r\n");
      out.write("				<strong>title</strong>\r\n");
      out.write("			</div>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"30%\" bgcolor=\"#ffcc00\">\r\n");
      out.write("			");
      out.print(paramTitle );
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("		<td width=\"10%\" bgcolor=\"#ffcc00\">\r\n");
      out.write("			<div align=\"right\"> \r\n");
      out.write("				<strong>Abstract</strong>\r\n");
      out.write("			</div>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"50%\" colspan=\"3\">\r\n");
      out.write("			<textarea rows=\"5\" cols=\"50\">\r\n");
      out.write("				");
      out.print(paramAbstract );
      out.write("\r\n");
      out.write("			</textarea>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"4\" bgcolor=\"#ffffff\">&nbsp;</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"4\"><strong>업로드된 파일</strong></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	");
for(int i=0;i<saveFiles.size();i++){ 
      out.write("\r\n");
      out.write("		<tr bgcolor=\"#ffcc00\">\r\n");
      out.write("			<td colspan=\"4\">\r\n");
      out.write("				<a href=");
      out.print("/ServletProject/"+saveFolder+"/"+saveFiles.get(i));
      out.write(">\r\n");
      out.write("					<strong>");
      out.print(origFiles.get(i) );
      out.write("</strong>\r\n");
      out.write("				</a>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("	<h2>업로드가 완료되었습니다.</h2>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li>User: ");
      out.print(paramUser);
      out.write("</li>\r\n");
      out.write("		<li>Title: ");
      out.print(paramTitle);
      out.write("</li>\r\n");
      out.write("		<li>Abstract: ");
      out.print(paramAbstract);
      out.write("</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

	}catch(IOException e){
		e.printStackTrace();
	}catch(Exception ee){
		ee.printStackTrace();
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
